server:
  port: 8082

# Configurações Application e H2 Database
spring:
  application:
    name: spring-boot-openapi-demo
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:flow-cortex-db
    driverClassName: org.h2.Driver
    username: chronus
    password: senh@123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true

# Configurações do SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false

# Configuração de logs detalhada
logging:
  level:
    # SQL queries
    org.hibernate.SQL: DEBUG

    # Parâmetros das queries (valores dos bind parameters)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    # Resultados das queries
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

    # Transações
    org.hibernate.transaction: DEBUG

    # Cache de segundo nível (se usado)
    org.hibernate.cache: DEBUG

    # Estatísticas do Hibernate
    org.hibernate.stat: DEBUG

    # Engine do Hibernate
    org.hibernate.engine: DEBUG

    # Root logger para sua aplicação
    com.seupackage: DEBUG

jwt:
  secret: afsdkjasjflxswafsdklk434orqiwup3457u-34oewir4irroqwiffv48mfs
  expiration: 3600

app:
  auth:
    service:
      url: http://localhost:8000

feign:
  client:
    config:
      auth-service:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
